-- =========================================================
-- ColdStack — Extensions, Enums, Types, Core Tables, Trips
-- =========================================================

-- 1) Extensions, Enums & Types
CREATE EXTENSION IF NOT EXISTS postgis;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'user_role') THEN
    CREATE TYPE user_role AS ENUM ('admin', 'carrier', 'shipper', 'consignee');
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'trip_status') THEN
    CREATE TYPE trip_status AS ENUM (
      'pending', 'assigned', 'en_route', 'on_trip', 'completed', 'cancelled'
    );
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'logger_status') THEN
    CREATE TYPE logger_status AS ENUM ('warehouse', 'maintenance', 'active', 'ready');
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'stack_status') THEN
    CREATE TYPE stack_status AS ENUM ('warehouse', 'cleaning', 'active', 'ready', 'maintenance');
  END IF;
END $$;

-- =========================================================
-- 2) Core Tables
-- =========================================================

-- profiles: extends auth.users (1:1 by id)
CREATE TABLE IF NOT EXISTS public.profiles (
  id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  full_name text,
  role user_role NOT NULL DEFAULT 'shipper',
  email text,
  phone text,
  onboarding_completed boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- loggers
CREATE TABLE IF NOT EXISTS public.loggers (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  serial text UNIQUE NOT NULL,
  status logger_status NOT NULL DEFAULT 'ready',
  battery_level int,
  last_active timestamp,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- stacks
CREATE TABLE IF NOT EXISTS public.stacks (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  serial text UNIQUE NOT NULL,
  status stack_status NOT NULL DEFAULT 'ready',
  current_logger_id uuid REFERENCES public.loggers(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- locations (Address book)
CREATE TABLE IF NOT EXISTS public.locations (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  owner_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  label text NOT NULL,
  address_text text NOT NULL,
  coords geography(POINT, 4326),
  created_at timestamptz NOT NULL DEFAULT now()
);

-- =========================================================
-- 3) Trip System (with snapshots)
-- =========================================================

CREATE TABLE IF NOT EXISTS public.trips (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  shipper_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE RESTRICT,
  consignee_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE RESTRICT,
  carrier_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  stack_id uuid REFERENCES public.stacks(id) ON DELETE SET NULL,

  status trip_status NOT NULL DEFAULT 'pending',

  created_at timestamptz NOT NULL DEFAULT now(),
  started_at timestamptz,
  completed_at timestamptz,

  -- Snapshots (historical accuracy)
  origin_address_snapshot text NOT NULL,
  origin_coords_snapshot geography(POINT, 4326),
  destination_address_snapshot text NOT NULL,
  destination_coords_snapshot geography(POINT, 4326)
);

-- =========================================================
-- 4) Data & Analytics
-- =========================================================

CREATE TABLE IF NOT EXISTS public.trip_photos (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  trip_id uuid NOT NULL REFERENCES public.trips(id) ON DELETE CASCADE,

  start_photo_url text,
  end_photo_url text,

  start_captured_at timestamp,
  end_captured_at timestamp,

  created_at timestamptz NOT NULL DEFAULT now()
);

-- telemetry: high-frequency inserts
CREATE TABLE IF NOT EXISTS public.telemetry (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  trip_id uuid NOT NULL REFERENCES public.trips(id) ON DELETE CASCADE,

  temperature decimal,
  coords geography(POINT, 4326),

  logged_at timestamptz NOT NULL DEFAULT now(),

  created_at timestamptz NOT NULL DEFAULT now(),

  -- Constraint to guard bad timestamps (helps keep insert stream sane)
  CONSTRAINT telemetry_logged_at_reasonable CHECK (
    logged_at <= (now() + interval '5 minutes')
  )
);

-- POC certificates
CREATE TABLE IF NOT EXISTS public.poc_certificates (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  trip_id uuid NOT NULL REFERENCES public.trips(id) ON DELETE CASCADE,

  pdf_url text NOT NULL,
  generated_at timestamp NOT NULL DEFAULT now(),
  verified_by_receiver boolean NOT NULL DEFAULT false,

  created_at timestamptz NOT NULL DEFAULT now()
);

-- KPIs
CREATE TABLE IF NOT EXISTS public.kpis (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  entity_id uuid NOT NULL,

  avg_temp_deviation decimal,
  on_time_trip_rate decimal,
  total_trips int,

  created_at timestamptz NOT NULL DEFAULT now()
);

-- =========================================================
-- 5) Relationships, Constraints & Logic
-- =========================================================

-- Indexes for common access + geospatial support
CREATE INDEX IF NOT EXISTS idx_locations_owner_id ON public.locations(owner_id);

CREATE INDEX IF NOT EXISTS idx_trips_shipper_id ON public.trips(shipper_id);
CREATE INDEX IF NOT EXISTS idx_trips_consignee_id ON public.trips(consignee_id);
CREATE INDEX IF NOT EXISTS idx_trips_carrier_id ON public.trips(carrier_id);
CREATE INDEX IF NOT EXISTS idx_trips_status ON public.trips(status);

CREATE INDEX IF NOT EXISTS idx_trip_photos_trip_id ON public.trip_photos(trip_id);

CREATE INDEX IF NOT EXISTS idx_telemetry_trip_id_logged_at
  ON public.telemetry(trip_id, logged_at DESC);

CREATE INDEX IF NOT EXISTS idx_telemetry_logged_at ON public.telemetry(logged_at DESC);

CREATE INDEX IF NOT EXISTS idx_poc_trip_id ON public.poc_certificates(trip_id);

-- =========================================================
-- Updated_at triggers (loggers, stacks)
-- =========================================================
CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_loggers_set_updated_at ON public.loggers;
CREATE TRIGGER trg_loggers_set_updated_at
BEFORE UPDATE ON public.loggers
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS trg_stacks_set_updated_at ON public.stacks;
CREATE TRIGGER trg_stacks_set_updated_at
BEFORE UPDATE ON public.stacks
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- =========================================================
-- Profile auto-creation on Auth signup
-- =========================================================

-- Creates a profile row when a user signs up via Supabase Auth.
-- Role defaults to 'shipper' (you can change it later via app logic).
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, auth
AS $$
BEGIN
  INSERT INTO public.profiles (id, full_name, role, email, phone, onboarding_completed, created_at)
  SELECT
    NEW.id,
    COALESCE(NEW.raw_user_meta_data->>'full_name', NULL),
    COALESCE((NEW.raw_user_meta_data->>'role')::user_role, 'shipper')::user_role,
    NEW.email,
    COALESCE(NEW.raw_user_meta_data->>'phone', NULL),
    FALSE,
    now()
  WHERE NOT EXISTS (
    SELECT 1 FROM public.profiles p WHERE p.id = NEW.id
  );

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
AFTER INSERT ON auth.users
FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- =========================================================
-- RLS Enablement
-- =========================================================
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.loggers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.stacks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.locations ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.trips ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.trip_photos ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.telemetry ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.poc_certificates ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.kpis ENABLE ROW LEVEL SECURITY;

-- =========================================================
-- RLS Policies
-- Rules:
-- - Admins: full access to all tables
-- - Carriers: only see trips assigned to them
-- - Shippers/Consignees: only see telemetry + POCs for trips linked to their IDs
--   (and for completeness, trip_photos can be limited to trip visibility as below)
-- =========================================================

-- Helper condition repeated in policies:
-- An admin is a user whose profiles.role = 'admin'
-- (auth.uid() is the current user's uuid)

-- ---------------------------
-- profiles
-- ---------------------------
CREATE POLICY "profiles_admin_full_access"
ON public.profiles
FOR ALL
TO authenticated
USING (
  EXISTS (
    SELECT 1 FROM public.profiles me
    WHERE me.id = auth.uid() AND me.role = 'admin'
  )
)
WITH CHECK (
  EXISTS (
    SELECT 1 FROM public.profiles me
    WHERE me.id = auth.uid() AND me.role = 'admin'
  )
);

CREATE POLICY "profiles_users_own_row_select"
ON public.profiles
FOR SELECT
TO authenticated
USING (id = auth.uid());

CREATE POLICY "profiles_users_own_row_update"
ON public.profiles
FOR UPDATE
TO authenticated
USING (id = auth.uid())
WITH CHECK (id = auth.uid());

-- ---------------------------
-- loggers
-- ---------------------------
CREATE POLICY "loggers_admin_full_access"
ON public.loggers
FOR ALL
TO authenticated
USING (
  EXISTS (SELECT 1 FROM public.profiles me WHERE me.id = auth.uid() AND me.role = 'admin')
)
WITH CHECK (
  EXISTS (SELECT 1 FROM public.profiles me WHERE me.id = auth.uid() AND me.role = 'admin')
);

-- ---------------------------
-- stacks
-- ---------------------------
CREATE POLICY "stacks_admin_full_access"
ON public.stacks
FOR ALL
TO authenticated
USING (
  EXISTS (SELECT 1 FROM public.profiles me WHERE me.id = auth.uid() AND me.role = 'admin')
)
WITH CHECK (
  EXISTS (SELECT 1 FROM public.profiles me WHERE me.id = auth.uid() AND me.role = 'admin')
);

-- ---------------------------
-- locations (owner-only, plus admin)
-- ---------------------------
CREATE POLICY "locations_admin_full_access"
ON public.locations
FOR ALL
TO authenticated
USING (
  EXISTS (SELECT 1 FROM public.profiles me WHERE me.id = auth.uid() AND me.role = 'admin')
)
WITH CHECK (
  EXISTS (SELECT 1 FROM public.profiles me WHERE me.id = auth.uid() AND me.role = 'admin')
);

CREATE POLICY "locations_owner_select"
ON public.locations
FOR SELECT
TO authenticated
USING (owner_id = auth.uid());

CREATE POLICY "locations_owner_insert"
ON public.locations
FOR INSERT
TO authenticated
WITH CHECK (owner_id = auth.uid());

CREATE POLICY "locations_owner_update"
ON public.locations
FOR UPDATE
TO authenticated
USING (owner_id = auth.uid())
WITH CHECK (owner_id = auth.uid());

-- ---------------------------
-- trips (admins full; carriers see assigned; shipper/consignee see linked)
-- ---------------------------
CREATE POLICY "trips_admin_full_access"
ON public.trips
FOR ALL
TO authenticated
USING (
  EXISTS (SELECT 1 FROM public.profiles me WHERE me.id = auth.uid() AND me.role = 'admin')
)
WITH CHECK (
  EXISTS (SELECT 1 FROM public.profiles me WHERE me.id = auth.uid() AND me.role = 'admin')
);

CREATE POLICY "trips_carrier_select_assigned"
ON public.trips
FOR SELECT
TO authenticated
USING (
  carrier_id = auth.uid()
);

CREATE POLICY "trips_shipper_select_linked"
ON public.trips
FOR SELECT
TO authenticated
USING (
  shipper_id = auth.uid()
);

CREATE POLICY "trips_consignee_select_linked"
ON public.trips
FOR SELECT
TO authenticated
USING (
  consignee_id = auth.uid()
);

-- (Optional) allow limited updates by admin only; otherwise default-deny.

-- ---------------------------
-- trip_photos (admins full; limited to users who can see the trip)
-- ---------------------------
CREATE POLICY "trip_photos_admin_full_access"
ON public.trip_photos
FOR ALL
TO authenticated
USING (
  EXISTS (SELECT 1 FROM public.profiles me WHERE me.id = auth.uid() AND me.role = 'admin')
)
WITH CHECK (
  EXISTS (SELECT 1 FROM public.profiles me WHERE me.id = auth.uid() AND me.role = 'admin')
);

CREATE POLICY "trip_photos_select_for_trip_participants"
ON public.trip_photos
FOR SELECT
TO authenticated
USING (
  EXISTS (
    SELECT 1
    FROM public.trips t
    WHERE t.id = trip_photos.trip_id
      AND (
        t.shipper_id = auth.uid()
        OR t.consignee_id = auth.uid()
        OR t.carrier_id = auth.uid()
      )
  )
);

-- ---------------------------
-- telemetry (admins full; shippers/consignees see telemetry for linked trips;
-- carriers see telemetry for trips assigned to them because they can see those trips too)
-- ---------------------------
CREATE POLICY "telemetry_admin_full_access"
ON public.telemetry
FOR ALL
TO authenticated
USING (
  EXISTS (SELECT 1 FROM public.profiles me WHERE me.id = auth.uid() AND me.role = 'admin')
)
WITH CHECK (
  EXISTS (SELECT 1 FROM public.profiles me WHERE me.id = auth.uid() AND me.role = 'admin')
);

CREATE POLICY "telemetry_select_shipper_consignee"
ON public.telemetry
FOR SELECT
TO authenticated
USING (
  EXISTS (
    SELECT 1
    FROM public.trips t
    WHERE t.id = telemetry.trip_id
      AND (
        t.shipper_id = auth.uid()
        OR t.consignee_id = auth.uid()
        OR t.carrier_id = auth.uid()
      )
  )
);

-- ---------------------------
-- poc_certificates (admins full; shippers/consignees see POCs for linked trips;
-- carriers see for trips assigned)
-- ---------------------------
CREATE POLICY "poc_admin_full_access"
ON public.poc_certificates
FOR ALL
TO authenticated
USING (
  EXISTS (SELECT 1 FROM public.profiles me WHERE me.id = auth.uid() AND me.role = 'admin')
)
WITH CHECK (
  EXISTS (SELECT 1 FROM public.profiles me WHERE me.id = auth.uid() AND me.role = 'admin')
);

CREATE POLICY "poc_select_shipper_consignee"
ON public.poc_certificates
FOR SELECT
TO authenticated
USING (
  EXISTS (
    SELECT 1
    FROM public.trips t
    WHERE t.id = poc_certificates.trip_id
      AND (
        t.shipper_id = auth.uid()
        OR t.consignee_id = auth.uid()
        OR t.carrier_id = auth.uid()
      )
  )
);

-- ---------------------------
-- kpis (admins full; otherwise keep it locked down by default)
-- ---------------------------
CREATE POLICY "kpis_admin_full_access"
ON public.kpis
FOR ALL
TO authenticated
USING (
  EXISTS (SELECT 1 FROM public.profiles me WHERE me.id = auth.uid() AND me.role = 'admin')
)
WITH CHECK (
  EXISTS (SELECT 1 FROM public.profiles me WHERE me.id = auth.uid() AND me.role = 'admin')
);

-- =========================================================
-- End of ColdStack schema
-- =========================================================


----- My modifications -----

-- Create the buckets
INSERT INTO storage.buckets (id, name, public) 
VALUES ('poc-certificates', 'poc-certificates', true),
       ('trip-photos', 'trip-photos', true);


-- Rls that that users are allowed to SELECT (read) and UPDATE (edit during onboarding) their own rows.
-- 1. Allow users to read their own profile
CREATE POLICY "Users can view their own profile" 
ON profiles 
FOR SELECT 
USING (auth.uid() = id);

-- 2. Allow users to update their own profile (crucial for /onboarding)
CREATE POLICY "Users can update their own profile" 
ON profiles 
FOR UPDATE 
USING (auth.uid() = id);

-- adding carrier_id to the stacks table
ALTER TABLE public.stacks
  ADD COLUMN IF NOT EXISTS carrier_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS idx_stacks_carrier_id ON public.stacks(carrier_id);



-- create shippers, consignee tables

-- 1. Create Shippers Table (Origins)
CREATE TABLE public.shippers (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    name TEXT NOT NULL,
    location_name TEXT NOT NULL,
    address TEXT NOT NULL,
    coords geography(POINT, 4326),
    -- latitude NUMERIC(10, 7) NOT NULL,
    -- longitude NUMERIC(10, 7) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- 2. Create Consignees Table (Destinations)
CREATE TABLE public.consignees (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    name TEXT NOT NULL,
    delivery_location_name TEXT NOT NULL,
    address TEXT NOT NULL,
    coords geography(POINT, 4326),
    -- latitude NUMERIC(10, 7) NOT NULL,
    -- longitude NUMERIC(10, 7) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- 3. Update Trips Table to handle the snapshots and relationships
ALTER TABLE public.trips 
    ADD COLUMN IF NOT EXISTS shipper_id uuid REFERENCES public.shippers(id) ON DELETE SET NULL,
    ADD COLUMN IF NOT EXISTS consignee_id uuid REFERENCES public.consignees(id) ON DELETE SET NULL,
    ADD COLUMN IF NOT EXISTS origin_name_snapshot TEXT,
    ADD COLUMN IF NOT EXISTS dest_name_snapshot TEXT,

-- 4. Enable RLS and grant access for Admins
ALTER TABLE public.shippers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.consignees ENABLE ROW LEVEL SECURITY;

CREATE POLICY "admin_shippers_all" ON public.shippers FOR ALL TO authenticated USING (public.is_admin(auth.uid()));
CREATE POLICY "admin_consignees_all" ON public.consignees FOR ALL TO authenticated USING (public.is_admin(auth.uid()));

GRANT SELECT, INSERT, UPDATE, DELETE ON public.shippers TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.consignees TO authenticated;

NOTIFY pgrst, 'reload_schema';

ALTER TABLE public.trips
  ADD COLUMN IF NOT EXISTS target_temp float4 NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS type_of_goods text NOT NULL DEFAULT 'unknown';

-- trips table now points shipper_id/consignee_id at shippers/consignees table. This schema is not yet updated but it has been updated in supabase.


-- Index these for high-performance dashboard lookups
CREATE INDEX IF NOT EXISTS idx_trips_carrier_id ON public.trips(carrier_id);
CREATE INDEX IF NOT EXISTS idx_trips_stack_id ON public.trips(stack_id);

-- fixing carrier rls on trips
-- 1. Grant Carriers the right to view and update trips assigned specifically to them
DROP POLICY IF EXISTS "carrier_select_own_trips" ON public.trips;
CREATE POLICY "carrier_select_own_trips" ON public.trips 
FOR SELECT TO authenticated USING (carrier_id = auth.uid());

DROP POLICY IF EXISTS "carrier_update_own_trips" ON public.trips;
CREATE POLICY "carrier_update_own_trips" ON public.trips 
FOR UPDATE TO authenticated USING (carrier_id = auth.uid());

-- 2. If Supabase created a strict check constraint on your status column, drop it
-- so it allows 'en_route' and 'on_trip' without crashing.
ALTER TABLE public.trips DROP CONSTRAINT IF EXISTS trips_status_check;

NOTIFY pgrst, 'reload_schema';

-- fixing rls for storage buckets and trip_photos
-- =========================================================
-- 1. STORAGE BUCKET POLICIES (Fixes the upload failure)
-- =========================================================

-- Allow authenticated carriers to upload images to the bucket
CREATE POLICY "Allow authenticated uploads" 
ON storage.objects FOR INSERT TO authenticated 
WITH CHECK (bucket_id = 'trip-photos');

-- Allow carriers to overwrite or update their uploads if needed
CREATE POLICY "Allow authenticated updates" 
ON storage.objects FOR UPDATE TO authenticated 
USING (bucket_id = 'trip-photos');

-- Allow authenticated users to view/read the uploaded public URLs
CREATE POLICY "Allow authenticated reads" 
ON storage.objects FOR SELECT TO authenticated 
USING (bucket_id = 'trip-photos');


-- =========================================================
-- 2. DATABASE TABLE POLICIES (Fixes trip_photos logging)
-- =========================================================

-- Ensure RLS is active on the trip_photos table
ALTER TABLE public.trip_photos ENABLE ROW LEVEL SECURITY;

-- Drop any stale or conflicting policies on this table
DROP POLICY IF EXISTS "carrier_manage_trip_photos" ON public.trip_photos;

-- Grant carriers full access to rows that belong to dispatches assigned to them
CREATE POLICY "carriers_manage_own_trip_photos" 
ON public.trip_photos FOR ALL TO authenticated 
USING (
    EXISTS (
        SELECT 1 FROM public.trips 
        WHERE trips.id = trip_photos.trip_id 
        AND trips.carrier_id = auth.uid()
    )
)
WITH CHECK (
    EXISTS (
        SELECT 1 FROM public.trips 
        WHERE trips.id = trip_photos.trip_id 
        AND trips.carrier_id = auth.uid()
    )
);

-- Grant direct table operation permissions to authenticated roles
GRANT SELECT, INSERT, UPDATE, DELETE ON public.trip_photos TO authenticated;

-- Refresh the PostgREST cache layer
NOTIFY pgrst, 'reload_schema';